default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: dic_work08_development
  host: localhost
  port: 5432

test:
  <<: *default
  adapter: postgresql
  database: dic_work08_test
production:
  <<: *default
  adapter: postgresql
  database: dic_work08_production
  username: dic_work08
  password: <%= ENV['DIC_WORK08_DATABASE_PASSWORD'] %>
